In [25]:
print("Question-1")

Question-1

In [4]:
import numpy as np

arr = np.arange(1,21)
print("Array :",arr)

Array : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

In [7]:
print("Shape:",arr.shape)

Shape: (20,)

In [8]:
min_val = min(arr)
max_val = max(arr)

print("Minimum value : ", min_val)
print("Maximun value : ", max_val)

Minimum value :  1
Maximun value :  20

In [14]:
mean_val = np.mean(arr)
print("Mean of the array :", mean_val)

std_dev = np.std(arr)
print("Standard Deviation :", std_dev)

Mean of the array : 10.5
Standard Deviation : 5.766281297335398

In [22]:
matrix = arr.reshape(4,5)
print("Reshaped array in 4x5 :\n",matrix)

Reshaped array in 4x5 :
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

In [23]:
print("Second row:", matrix[1])

Second row: [ 6  7  8  9 10]

In [24]:
print("Third column:", matrix[:,2])

Third column: [ 3  8 13 18]

In [26]:
print("Question-2")

Question-2

In [29]:
import numpy as np

A = np.array([10,20,30,40,50])
B = np.array([5,10,15,20,25])
print("Array of A:",A)
print("Array of B:",B)

Array of A: [10 20 30 40 50]
Array of B: [ 5 10 15 20 25]

In [37]:
print("Addition of A and B : ",A+B)
print("Subtraction of B form A: ",B-A)
print("Element wise Multiplication: ",A*B)
print("Element wise Division: ",A/B)
print("Sum of all elements in A: ", A.sum())

Addition of A and B :  [15 30 45 60 75]
Subtraction of B form A:  [ -5 -10 -15 -20 -25]
Element wise Multiplication:  [  50  200  450  800 1250]
Element wise Division:  [2. 2. 2. 2. 2.]
Sum of all elements in A:  150

In [38]:
print("Question-3")

Question-3

In [48]:
import pandas as pd 

data = {
    'Rollno': [101, 102, 103, 104, 105],
    'Name': ['Ravi', 'Priya', 'Kiran', 'Anu', 'Sita'],
    'Marks': [85, 92, 78, 88, 95]}
df = pd.DataFrame(data)
display(df)

   Rollno   Name  Marks
0     101   Ravi     85
1     102  Priya     92
2     103  Kiran     78
3     104    Anu     88
4     105   Sita     95

In [42]:
print("The first 3 records: ")
display(df.head(3))

The first 3 records:

   Rollno   Name  Marks
0     101   Ravi     85
1     102  Priya     92
2     103  Kiran     78

In [47]:
print("Average of Marks:", df["Marks"].mean())
print("Highest marks: ",df["Marks"].max())
print("Lowest marks:", df["Marks"].min())

Average of Marks: 87.6
Highest marks:  95
Lowest marks: 78

In [50]:
def grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 80:
        return "B"
    else:
        return "C"
df["Grade"] = df["Marks"].apply(grade)
print("DataFrame with Grade:\n", df)

DataFrame with Grade:
    Rollno   Name  Marks Grade
0     101   Ravi     85     B
1     102  Priya     92     A
2     103  Kiran     78     C
3     104    Anu     88     B
4     105   Sita     95     A

In [52]:
print("Question-4")

Question-4

In [55]:
import pandas as pd 

data2 = {
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
    'Price': [50000, 500, 1200, 10000],
    'Quantity': [10, 50, 30, 15]}
df = pd.DataFrame(data2)
display(df)

    Product  Price  Quantity
0    Laptop  50000        10
1     Mouse    500        50
2  Keyboard   1200        30
3   Monitor  10000        15

In [61]:
df['TotalValue'] = df['Price'] * df['Quantity']
grand_total = df['TotalValue'].sum()

print(df)

print("\nProduct with highest total value:",df['TotalValue'].max())
print("\nOverall inventory Value of Products:", grand_total)

    Product  Price  Quantity  TotalValue
0    Laptop  50000        10      500000
1     Mouse    500        50       25000
2  Keyboard   1200        30       36000
3   Monitor  10000        15      150000

Product with highest total value: 500000

Overall inventory Value of Products: 711000

In [63]:
print("Question-5")

Question-5

In [2]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["Species"] = iris.target
df["Species"] = df["Species"].map({
    0: "setosa",
    1: "versicolor",
    2: "virginica"
})
print("\nIris DataFrame:")
print(df)

print("\nFirst Five Records:")
print(df.head())

print("\nNumber of Rows and Columns:")
print(df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nSummary Statistics:")
print(df.describe())

print("\nSamples in Each Class:")
print(df["Species"].value_counts())

Iris DataFrame:
     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

       Species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 5 columns]

First Five Records:
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

  Species
0  setosa
1  setosa
2  setosa
3  setosa
4  setosa

Number of Rows and Columns:
(150, 5)

Column Names:
Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'Species'],
      dtype='object')

Missing Values:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
Species              0
dtype: int64

Summary Statistics:
       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000
mean            5.843333          3.057333           3.758000
std             0.828066          0.435866           1.765298
min             4.300000          2.000000           1.000000
25%             5.100000          2.800000           1.600000
50%             5.800000          3.000000           4.350000
75%             6.400000          3.300000           5.100000
max             7.900000          4.400000           6.900000

       petal width (cm)
count        150.000000
mean           1.199333
std            0.762238
min            0.100000
25%            0.300000
50%            1.300000
75%            1.800000
max            2.500000

Samples in Each Class:
Species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64